# Generated by Django 4.1.5 on 2023-03-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_c',
            field=models.TextField(null=True),
        ),
    ]
