# Generated by Django 4.1.5 on 2023-03-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_person_user_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='token',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_c',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
