# Generated by Django 4.1.5 on 2023-03-20 17:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message_token_person_user_c'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='message',
        #     name='answer',
        #     field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        # ),
    ]
