# Generated by Django 4.1.5 on 2023-03-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_message_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
