# Generated by Django 4.1.5 on 2023-03-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_message_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isKazakh',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
