# Generated by Django 4.1.5 on 2023-04-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_message_conv_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversations',
            old_name='id_pk',
            new_name='conv_id',
        ),
    ]
